#! python3
"""Executable for autocompleting file"""

from logging import getLogger, basicConfig, INFO, DEBUG
from pathlib import Path
from sys import argv

from gramolang import OpenAIWrapper
from gramolang.auto import complete_file


# API keys
api_key_files = {
    OpenAIWrapper: Path(__file__).parent / '.keys' / 'openai-api-key-uqam'}

# Settings
MODEL = 'gpt-3.5-turbo'     # Default model
TIMEOUT = 2 * 60            # Max. time in seconds for one chat completion
RETRIES = 4                 # Number of times to retries on timeout or rate limit
MAX_CHATS = None            # Max. concurrent conversations for each file (None for default)
LOG_LEVEL = INFO            # Logging level (must import from logging)

# Logging
getLogger('gramolang').setLevel(LOG_LEVEL)
if LOG_LEVEL is DEBUG:
    basicConfig(
        format='%(asctime)s [%(module)s][%(name)s] %(message)s')
else:
    basicConfig(format='%(message)s', datefmt='%X')

# Process command line arguments
if len(argv) == 1:
    print("Missing 1 required argument: file path")
    exit(1)
if len(argv) > 3:
    print(
        f"Too many command line arguments: "
        f"{len(argv) - 1} provided and 2 allowed.")
    exit(1)

# Call
try: complete_file(
    path=Path(argv[1]), new_path=Path(argv[2]) if len(argv) == 3 else None,
    api_key_files=api_key_files, model=MODEL,
    timeout=TIMEOUT, retries=RETRIES, max_chats=MAX_CHATS)
except Exception as e:
    print(e)
    exit(1)
