#! python3
"""Executable for interactive console"""

from pathlib import Path

from gramolang import OpenAIAPIWrapper
from gramolang.console import Console


# API Keys
api_key_files = {
    OpenAIAPIWrapper: Path(__file__).parent / '.keys' / 'openai-api-key-uqam'}

# Settings
MODEL = 'gpt-4'

# Create and start console
console = Console(api_key_files=api_key_files)
console.model(MODEL)
console.run()
